"use client";

import { useState } from "react";
import type { RecommendationDetail, ReviewRecord } from "@/types/api";
import { reviewRecommendation } from "@/lib/api/recommendations";
import { StatusBadge } from "@/components/ui/StatusBadge";

export function ReviewPanel({ recommendation, history, onReviewed }: { recommendation: RecommendationDetail; history: ReviewRecord[]; onReviewed: () => Promise<void> }) {
  const [comment, setComment] = useState("");
  const [submitting, setSubmitting] = useState<"approve" | "reject" | null>(null);
  const [error, setError] = useState<string | null>(null);
  async function submit(decision: "approve" | "reject") { setSubmitting(decision); setError(null); try { await reviewRecommendation(recommendation.id, decision, comment); setComment(""); await onReviewed(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Review could not be saved."); } finally { setSubmitting(null); } }
  return <section className="glass rounded-3xl p-6 sm:p-8" aria-labelledby="human-review"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">Editorial decision</p><h2 id="human-review" className="display mt-2 text-3xl font-bold">Human Review</h2></div><StatusBadge status={recommendation.human_review_state} /></div>
    {recommendation.human_review_permitted ? <div className="mt-6"><label htmlFor="review-comment" className="mb-2 block text-sm font-bold">Optional review comment</label><textarea id="review-comment" className="field resize-y" rows={4} maxLength={2000} value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Add editorial context for this decision…" /><div className="mt-4 flex flex-wrap gap-3"><button className="btn-primary" disabled={submitting !== null} onClick={() => void submit("approve")}>{submitting === "approve" ? "Approving…" : "Approve"}</button><button className="btn-danger" disabled={submitting !== null} onClick={() => void submit("reject")}>{submitting === "reject" ? "Rejecting…" : "Reject"}</button></div>{error && <p role="alert" className="mt-3 text-sm text-red-200">{error}</p>}</div> : <div className="mt-6 rounded-2xl border border-red-300/20 bg-red-300/[.06] p-5"><p className="font-bold text-red-100">Human approval is not permitted</p><p className="muted mt-2 text-sm">This candidate was rejected by the deterministic guard and cannot be approved. The immutable evidence remains available for inspection.</p></div>}
    <div className="mt-8 border-t border-white/8 pt-6"><h3 className="display text-lg font-bold">Review history</h3><ol className="mt-4 space-y-0"><li className="relative border-l border-white/12 pb-5 pl-6"><span className="absolute -left-1.5 top-1 size-3 rounded-full border border-slate-400 bg-slate-800" /><p className="font-semibold">Pending</p><p className="muted text-xs">Recommendation persisted for review</p></li>{history.map((review) => <li className="relative border-l border-white/12 pb-5 pl-6 last:border-transparent" key={review.id}><span className={`absolute -left-1.5 top-1 size-3 rounded-full border ${review.decision === "approved" ? "border-emerald-200 bg-emerald-400" : "border-red-200 bg-red-400"}`} /><div className="flex flex-wrap items-center gap-2"><p className="font-semibold capitalize">{review.decision}</p><time className="muted text-xs" dateTime={review.created_at}>{new Date(review.created_at).toLocaleString()}</time></div>{review.comment && <blockquote className="muted mt-1 text-sm">“{review.comment}”</blockquote>}</li>)}</ol></div>
  </section>;
}
